### ISSUE TITLE
Allow changing the loading icon for all toasts

### ISSUE THREAD

**Issue by charlieandroid55** [tutkli/ngx-sonner#10]
### Information

Currently the documentation offers a way to change the icon but it is individual for each toast, what if I need to customize all my loading and promise toasts to have that icon?

Could be achieved through one of these variants
```html
  <ngx-sonner-toaster [icon]="iconTemplate"/>
```  
```html
  <ngx-sonner-toaster>
      <custom-icon sonnerLoadingIcon/>
   <ngx-sonner-toaster/> 
``` 

if the icon is specified in the toast it can override the global 
```typescript
toast('Event has been created', {
	description: 'Monday, January 3rd at 6:00pm',
	icon: IconComponent
});
``` 

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by tutkli** [comment]
Hi, @charlieandroid55 ! This feature will be available in Angular v18 and [ng-content default content](https://github.com/angular/angular/issues/12530)

**Comment by charlieandroid55** [comment]
Hi @tutkli, do you have any suggestions for working around this issue?

**Comment by tutkli** [comment]
The easiest way I see is to wrap the toast function to always use your custom icon in case the toast is a promise or is loading. Something like:

```ts
function customLoadingToast(message: string | Type<unknown>, data?: ExternalToast) {
  return toast.loading(message, {...data, icon: LoadingIconComponent }
}
```

I've been thinking about this and I know this isn't pretty. The icon API could use some improvements and the best solution without making any breaking changes is to wait for ng-content placeholder.

Sorry for the inconvenience, I'll leave this open until then.

**Comment by charlieandroid55** [comment]
Thanks for the solution, am currently using the default icon, because if i do this I will have to create custom wrappers for each one to maintain a standard toast API, doing this is not a big problem but I'm already waiting for the new support, thank you for everything, great work with this component
