### ISSUE TITLE
Dismissable setting doesn't work both ways

### ISSUE THREAD

**Issue by charlieandroid55** [tutkli/ngx-sonner#14]
### Please provide the environment you discovered this bug in.

```html
<ngx-sonner-toaster closeButton="false"/>
``` 
```typescript
 toast.error('Error toast', {dismissable: true});
``` 

### Description

The dismissable configuration, which is managed at the instance level, in my opinion, should override the global closeButton configuration in both directions. If I set closeButton to true, I expect most of my toasts to have that action, except for a few that cannot be closed. However, if I set closeButton to false, I mean that none of them should be closable by default, except for the one that has dismissable set to true. This way, I would have control over when and how a toast can be dismissed. 

Currently, the behavior works as expected in version 0.4.1 for the following configuration: closeButton=true | dismissable=false. 

However, the following configuration needs to be implemented: closeButton=false | dismissable=true.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by tutkli** [comment]
Hi, @charlieandroid55 ! The `dismissible` property of the toast refer to the ability to swipe out a toast, which is currently not working (Fixing it in #16 ).

For this, I'll add a `closeButton` property to the toastOptions, so you can override the toaster config.

1. Toast don't have a close button by default, except when instatiating then with `closeButton: true`:
```html
<ngx-sonner-toaster closeButton="false"/>
```
```ts
toast('Some message', {closeButton: true});
```

2. Toasts have a closeButton by default, but can be hidden when instatiating with `closeButton: false`
```html
<ngx-sonner-toaster closeButton />
```
```ts
toast('Some message', {closeButton: false});
```

**Comment by tutkli** [comment]
I understand, but I think it's okay to have the two options as they are two diferent actions. Adds more customization.
The original API is also like this, and I did not included it in first time.

Bear with me as this is the first angular port I make , but I'm trying to make it as best as possible 😅
