### ISSUE TITLE
How to call it from a Child-Component?

### ISSUE THREAD

**Issue by dertuerke** [tutkli/ngx-sonner#19]
Hi, how i can call the toast from a Child Route/Component if i place the toast inside the app.component?

Dont see any service to call it.

**Comment by dertuerke** [comment]
@tutkli love you 💋 Thx it works.

**Comment by tutkli** [comment]
For headless toasts you can use `toast.custom()` function and pass the component that you want to render.
Here's an example using Daisy UI :)

[Stackblitz](https://stackblitz.com/edit/stackblitz-starters-taoom4?file=src%2Fmain.ts,src%2Ftoast.component.ts)

**Comment by dertuerke** [comment]
Maaaaaaaaannnnnnnnnnnnnnny thx for the example.
