### ISSUE TITLE
Position inconsistency

### ISSUE THREAD

**Issue by DevWedeloper** [tutkli/ngx-sonner#23]
### Please provide the environment you discovered this bug in.

I noticed this bug when working with spartan.ng sonner, which is just a wrapper of this library. Here's a [minimal repo](https://github.com/DevWedeloper/ngx-sonner-position-bug).

### Description

There seems to be some inconsistencies of the direction which the sonner is coming from. By default the position is "bottom-right", making a toast callback with any top position makes it so that the direction is opposite (instead of appearing top to bottom, it's appearing bottom to top). The effect is also the same if the position of ngx-sonner is set to top, and the toast position is set to bottom.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by tutkli** [comment]
Thank you for reporting this! I will take a look into it a soon as I can
