### ISSUE TITLE
Hope support for angular v16 or below

### ISSUE THREAD

**Issue by Sariln** [tutkli/ngx-sonner#24]
### Information

My Project has build on angular version 15 and 16, I hope I can use Sonner in my project. Thank you

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by tutkli** [comment]
Hi, 
the project relies on features of Angular v17 and v18 in several places. I don't see the benefit of undergrading. I think It's best to keep up with the latest Angular versions.
