### ISSUE TITLE
Add support for Angular 19 compatibility

### ISSUE THREAD

**Issue by AngelCareaga** [tutkli/ngx-sonner#30]
### Information

Hello there! 😊 I recently tried using ngx-sonner with Angular 19, but I ran into some issues, and I’m not sure if additional configuration is needed or if ngx-sonner isn’t fully compatible with this version yet. I’ve done my best to troubleshoot, but I still can’t get it working smoothly.

Would it be possible to add official support for Angular 19? It would be a huge help, as we’d love to keep our project up-to-date with the latest version of Angular without needing workarounds. Thank you so much for considering this request! 🙏

### Describe any alternatives/workarounds you're currently using

For now, I’ve reverted to Angular 18 to avoid compatibility issues with ngx-sonner. I also tried some manual adjustments, but that led to instability in the app. An official update would make things a lot easier for us.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by tutkli** [comment]
Hi! Angular 18 should be compatible with this lib out of the box. What issues did you run into?

**Comment by charlieandroid55** [comment]
Hi @tutkli , I'm also experiencing problems after upgrading to v19. For some reason, the toasts aren't displayed; only the promise type works. Even the success and error messages thrown at the end of the promise work correctly, but any other type of toast thrown individually isn't displayed.

I'm using it through `spartan-ng`, and in v19 it doesn't work for me. I downgraded to v18.2.4, which was the version I had before, and it works correctly.

**Comment by tutkli** [comment]
I'll be looking into this. Please, have some patience since Angular 19 released literally yesterday :)

**Comment by samuelkrupik** [comment]
Hi @tutkli, I was trying to figure out what the problem might be. The [timing of effects](https://blog.angular.dev/latest-updates-to-effect-in-angular-f2d2648defcd) have changed in Angular 19. I'm not sure, but it looks like the [effect](https://github.com/tutkli/ngx-sonner/blob/cc5831aea7905999e2949e19c53fe9f559f1155e/libs/ngx-sonner/src/lib/toast.component.ts#L306) in which timer is handled, is executed before the [remainingTime](https://github.com/tutkli/ngx-sonner/blob/cc5831aea7905999e2949e19c53fe9f559f1155e/libs/ngx-sonner/src/lib/toast.component.ts#L326) is set in NgAfterViewInit, which results in the toast being removed immediately. This new API might be useful: https://angular.dev/api/core/afterRenderEffect#. Hope this helps :)

**Comment by tutkli** [comment]
Thank you @samuelkrupik it seems like that is actually the issue. 
I want to wait until nx is compatible with Angular 19 though. It's already in progess.

**Comment by marcindz88** [comment]
@tutkli Hi there, Are you working on this issue? I think that NX is already compatible with NG 19.
