### ISSUE TITLE
Animations broken

### ISSUE THREAD

**Issue by Dafnik** [tutkli/ngx-sonner#33]
### Please provide the environment you discovered this bug in.

Private project and demo https://tutkli.github.io/ngx-sonner/.

 with Angular v19 and ngx-sooner v3.

### Description

Even tho the functionality works, the animations are gone.

### Please provide the exception or error you saw

```true
No error thrown.
```

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by tutkli** [comment]
Hi! I can see the animations working in the demo page. Is an specific animation that is not working? Can you point it out?
